dist: trusty
sudo: false

language: php

env:
  global:
    - COMPOSER_ARGS="--ansi --prefer-dist --no-interaction --no-suggest --no-progress --optimize-autoloader"
    - DEPS="phpunit/phpunit squizlabs/php_codesniffer php-coveralls/php-coveralls johnkary/phpunit-speedtrap"

git:
  depth: 3

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
  include:
    - php: 7.0
    - php: 7.1
      env: ANALYSIS="true"
    - php: 7.2
    - php: hhvm
    - php: nightly

before_script:
  - composer require --dev $COMPOSER_ARGS $DEPS

script:
  - php vendor/bin/phpunit
  - if [[ "$ANALYSIS" == "true" ]]; then php vendor/bin/phpcs ; fi

after_script:
  - if [[ "$ANALYSIS" == "true" && -f ./build/logs/clover.xml ]]; then php vendor/bin/php-coveralls -v; fi
